version: '3'
services:

  #PHP Service
  app:
    image: "$DOCKER_IMAGE_PROD"
    #image: drupal:8.8.8-fpm-buster
    container_name: app
    restart: unless-stopped
    depends_on:
      - mariadb
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/web
    ports:
      - "9001:9000"
    volumes:
      #- ./drupal:/var/www
      - ./local-prod.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: "$DOCKER_IMAGE_NGINX_PROD"
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - app
      - mariadb
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./drupal/web:/var/www/html
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/logs:/var/log/nginx
    networks:
      - app-network

  #MySQL Service
  mariadb:
    image: mariadb:10.5.5-focal
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./volumes/mariadb:/var/lib/mysql/
      - ./my.cnf:/etc/mysql/my.cnf
      - ./volumes/mariadb-tmp:/tmp
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local