FROM nginx:alpine

# Copiando Drupal
ENV DRUPAL_VERSION 8.9.3
USER root
RUN mkdir /drupal
COPY ../drupal /drupal
RUN set -eux; \
    mkdir /var/www; \
    cp -rp /drupal/* /var/www/
RUN set -eux; \
    chmod -R 755 /var/www; \
    chown -R www-data:www-data /var/www
# RUN mkdir /var/www/web/sites/default/files
# Copiando el fichero de configuración
COPY settings.php web/sites/default
RUN set -eux; \
    chmod -R 640 web/sites/default/settings.php; \
    chown -R www-data:www-data web/sites/default/settings.php; \
	rmdir /var/www/html; \
	ln -sf /var/www/web /var/www/html;


